=begin
#Commercetools

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: undefined

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0

=end

require 'date'
require 'time'

module CtSdk
  class AnonymousCartSignInMode
    MERGE_WITH_EXISTING_CUSTOMER_CART = "MergeWithExistingCustomerCart".freeze
    USE_AS_NEW_ACTIVE_CUSTOMER_CART = "UseAsNewActiveCustomerCart".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = AnonymousCartSignInMode.constants.select { |c| AnonymousCartSignInMode::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #AnonymousCartSignInMode" if constantValues.empty?
      value
    end
  end
end
