=begin
#Commercetools

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: undefined

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0

=end

require 'date'
require 'time'

module CtSdk
  class CartDraft
    # The currency code compliant to [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217).
    attr_accessor :currency

    # Id of an existing Customer.
    attr_accessor :customer_id

    attr_accessor :customer_email

    attr_accessor :customer_group

    # Assigns the new cart to an anonymous session (the customer has not signed up/in yet).
    attr_accessor :anonymous_id

    attr_accessor :store

    # A two-digit country code as per [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2).
    attr_accessor :country

    attr_accessor :inventory_mode

    attr_accessor :tax_mode

    attr_accessor :tax_rounding_mode

    attr_accessor :tax_calculation_mode

    attr_accessor :line_items

    attr_accessor :custom_line_items

    attr_accessor :shipping_address

    attr_accessor :billing_address

    attr_accessor :shipping_method

    attr_accessor :external_tax_rate_for_shipping_method

    attr_accessor :custom

    # Must be one of the languages supported for this project
    attr_accessor :locale

    # The cart will be deleted automatically if it hasn't been modified for the specified amount of days and it is in the `Active` CartState. If a ChangeSubscription for carts exists, a `ResourceDeleted` notification will be sent.
    attr_accessor :delete_days_after_last_modification

    attr_accessor :origin

    attr_accessor :shipping_rate_input

    # Contains addresses for carts with multiple shipping addresses. Each address must contain a key which is unique in this cart. Line items will use these keys to reference the addresses under their `shippingDetails`. The addresses captured here are not used to determine eligible shipping methods or the applicable tax rate. Only the cart's `shippingAddress` is used for this.
    attr_accessor :item_shipping_addresses

    # The code of existing DiscountCodes.
    attr_accessor :discount_codes

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'currency' => :'currency',
        :'customer_id' => :'customerId',
        :'customer_email' => :'customerEmail',
        :'customer_group' => :'customerGroup',
        :'anonymous_id' => :'anonymousId',
        :'store' => :'store',
        :'country' => :'country',
        :'inventory_mode' => :'inventoryMode',
        :'tax_mode' => :'taxMode',
        :'tax_rounding_mode' => :'taxRoundingMode',
        :'tax_calculation_mode' => :'taxCalculationMode',
        :'line_items' => :'lineItems',
        :'custom_line_items' => :'customLineItems',
        :'shipping_address' => :'shippingAddress',
        :'billing_address' => :'billingAddress',
        :'shipping_method' => :'shippingMethod',
        :'external_tax_rate_for_shipping_method' => :'externalTaxRateForShippingMethod',
        :'custom' => :'custom',
        :'locale' => :'locale',
        :'delete_days_after_last_modification' => :'deleteDaysAfterLastModification',
        :'origin' => :'origin',
        :'shipping_rate_input' => :'shippingRateInput',
        :'item_shipping_addresses' => :'itemShippingAddresses',
        :'discount_codes' => :'discountCodes'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'currency' => :'String',
        :'customer_id' => :'String',
        :'customer_email' => :'String',
        :'customer_group' => :'CustomerGroupResourceIdentifier',
        :'anonymous_id' => :'String',
        :'store' => :'StoreResourceIdentifier',
        :'country' => :'String',
        :'inventory_mode' => :'InventoryMode',
        :'tax_mode' => :'TaxMode',
        :'tax_rounding_mode' => :'RoundingMode',
        :'tax_calculation_mode' => :'TaxCalculationMode',
        :'line_items' => :'Array<LineItemDraft>',
        :'custom_line_items' => :'Array<CustomLineItemDraft>',
        :'shipping_address' => :'Address',
        :'billing_address' => :'Address',
        :'shipping_method' => :'ShippingMethodResourceIdentifier',
        :'external_tax_rate_for_shipping_method' => :'ExternalTaxRateDraft',
        :'custom' => :'CustomFieldsDraft',
        :'locale' => :'String',
        :'delete_days_after_last_modification' => :'Integer',
        :'origin' => :'CartOrigin',
        :'shipping_rate_input' => :'ShippingRateInputDraft',
        :'item_shipping_addresses' => :'Array<Address>',
        :'discount_codes' => :'Array<String>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `CtSdk::CartDraft` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `CtSdk::CartDraft`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'currency')
        self.currency = attributes[:'currency']
      end

      if attributes.key?(:'customer_id')
        self.customer_id = attributes[:'customer_id']
      end

      if attributes.key?(:'customer_email')
        self.customer_email = attributes[:'customer_email']
      end

      if attributes.key?(:'customer_group')
        self.customer_group = attributes[:'customer_group']
      end

      if attributes.key?(:'anonymous_id')
        self.anonymous_id = attributes[:'anonymous_id']
      end

      if attributes.key?(:'store')
        self.store = attributes[:'store']
      end

      if attributes.key?(:'country')
        self.country = attributes[:'country']
      end

      if attributes.key?(:'inventory_mode')
        self.inventory_mode = attributes[:'inventory_mode']
      end

      if attributes.key?(:'tax_mode')
        self.tax_mode = attributes[:'tax_mode']
      end

      if attributes.key?(:'tax_rounding_mode')
        self.tax_rounding_mode = attributes[:'tax_rounding_mode']
      end

      if attributes.key?(:'tax_calculation_mode')
        self.tax_calculation_mode = attributes[:'tax_calculation_mode']
      end

      if attributes.key?(:'line_items')
        if (value = attributes[:'line_items']).is_a?(Array)
          self.line_items = value
        end
      end

      if attributes.key?(:'custom_line_items')
        if (value = attributes[:'custom_line_items']).is_a?(Array)
          self.custom_line_items = value
        end
      end

      if attributes.key?(:'shipping_address')
        self.shipping_address = attributes[:'shipping_address']
      end

      if attributes.key?(:'billing_address')
        self.billing_address = attributes[:'billing_address']
      end

      if attributes.key?(:'shipping_method')
        self.shipping_method = attributes[:'shipping_method']
      end

      if attributes.key?(:'external_tax_rate_for_shipping_method')
        self.external_tax_rate_for_shipping_method = attributes[:'external_tax_rate_for_shipping_method']
      end

      if attributes.key?(:'custom')
        self.custom = attributes[:'custom']
      end

      if attributes.key?(:'locale')
        self.locale = attributes[:'locale']
      end

      if attributes.key?(:'delete_days_after_last_modification')
        self.delete_days_after_last_modification = attributes[:'delete_days_after_last_modification']
      end

      if attributes.key?(:'origin')
        self.origin = attributes[:'origin']
      end

      if attributes.key?(:'shipping_rate_input')
        self.shipping_rate_input = attributes[:'shipping_rate_input']
      end

      if attributes.key?(:'item_shipping_addresses')
        if (value = attributes[:'item_shipping_addresses']).is_a?(Array)
          self.item_shipping_addresses = value
        end
      end

      if attributes.key?(:'discount_codes')
        if (value = attributes[:'discount_codes']).is_a?(Array)
          self.discount_codes = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @currency.nil?
        invalid_properties.push('invalid value for "currency", currency cannot be nil.')
      end

      pattern = Regexp.new(/^[A-Z]{3}$/)
      if @currency !~ pattern
        invalid_properties.push("invalid value for \"currency\", must conform to the pattern #{pattern}.")
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @currency.nil?
      return false if @currency !~ Regexp.new(/^[A-Z]{3}$/)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] currency Value to be assigned
    def currency=(currency)
      if currency.nil?
        fail ArgumentError, 'currency cannot be nil'
      end

      pattern = Regexp.new(/^[A-Z]{3}$/)
      if currency !~ pattern
        fail ArgumentError, "invalid value for \"currency\", must conform to the pattern #{pattern}."
      end

      @currency = currency
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          currency == o.currency &&
          customer_id == o.customer_id &&
          customer_email == o.customer_email &&
          customer_group == o.customer_group &&
          anonymous_id == o.anonymous_id &&
          store == o.store &&
          country == o.country &&
          inventory_mode == o.inventory_mode &&
          tax_mode == o.tax_mode &&
          tax_rounding_mode == o.tax_rounding_mode &&
          tax_calculation_mode == o.tax_calculation_mode &&
          line_items == o.line_items &&
          custom_line_items == o.custom_line_items &&
          shipping_address == o.shipping_address &&
          billing_address == o.billing_address &&
          shipping_method == o.shipping_method &&
          external_tax_rate_for_shipping_method == o.external_tax_rate_for_shipping_method &&
          custom == o.custom &&
          locale == o.locale &&
          delete_days_after_last_modification == o.delete_days_after_last_modification &&
          origin == o.origin &&
          shipping_rate_input == o.shipping_rate_input &&
          item_shipping_addresses == o.item_shipping_addresses &&
          discount_codes == o.discount_codes
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [currency, customer_id, customer_email, customer_group, anonymous_id, store, country, inventory_mode, tax_mode, tax_rounding_mode, tax_calculation_mode, line_items, custom_line_items, shipping_address, billing_address, shipping_method, external_tax_rate_for_shipping_method, custom, locale, delete_days_after_last_modification, origin, shipping_rate_input, item_shipping_addresses, discount_codes].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = CtSdk.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
