=begin
#Commercetools

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: undefined

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0

=end

require 'date'
require 'time'

module CtSdk
  class ProductProjectionAllOf
    # The unique ID of the Product.
    attr_accessor :id

    # The current version of the Product.
    attr_accessor :version

    attr_accessor :created_at

    attr_accessor :last_modified_at

    # User-specific unique identifier of the Product.
    attr_accessor :key

    attr_accessor :product_type

    attr_accessor :name

    attr_accessor :description

    attr_accessor :slug

    # References to categories the product is in.
    attr_accessor :categories

    attr_accessor :category_order_hints

    attr_accessor :meta_title

    attr_accessor :meta_description

    attr_accessor :meta_keywords

    attr_accessor :search_keywords

    attr_accessor :has_staged_changes

    attr_accessor :published

    attr_accessor :master_variant

    attr_accessor :variants

    attr_accessor :tax_category

    attr_accessor :state

    attr_accessor :review_rating_statistics

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'version' => :'version',
        :'created_at' => :'createdAt',
        :'last_modified_at' => :'lastModifiedAt',
        :'key' => :'key',
        :'product_type' => :'productType',
        :'name' => :'name',
        :'description' => :'description',
        :'slug' => :'slug',
        :'categories' => :'categories',
        :'category_order_hints' => :'categoryOrderHints',
        :'meta_title' => :'metaTitle',
        :'meta_description' => :'metaDescription',
        :'meta_keywords' => :'metaKeywords',
        :'search_keywords' => :'searchKeywords',
        :'has_staged_changes' => :'hasStagedChanges',
        :'published' => :'published',
        :'master_variant' => :'masterVariant',
        :'variants' => :'variants',
        :'tax_category' => :'taxCategory',
        :'state' => :'state',
        :'review_rating_statistics' => :'reviewRatingStatistics'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'version' => :'Integer',
        :'created_at' => :'Time',
        :'last_modified_at' => :'Time',
        :'key' => :'String',
        :'product_type' => :'ProductTypeReference',
        :'name' => :'Object',
        :'description' => :'Object',
        :'slug' => :'Object',
        :'categories' => :'Array<CategoryReference>',
        :'category_order_hints' => :'Object',
        :'meta_title' => :'Object',
        :'meta_description' => :'Object',
        :'meta_keywords' => :'Object',
        :'search_keywords' => :'Object',
        :'has_staged_changes' => :'Boolean',
        :'published' => :'Boolean',
        :'master_variant' => :'ProductVariant',
        :'variants' => :'Array<ProductVariant>',
        :'tax_category' => :'TaxCategoryReference',
        :'state' => :'StateReference',
        :'review_rating_statistics' => :'ReviewRatingStatistics'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `CtSdk::ProductProjectionAllOf` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `CtSdk::ProductProjectionAllOf`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'version')
        self.version = attributes[:'version']
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      end

      if attributes.key?(:'last_modified_at')
        self.last_modified_at = attributes[:'last_modified_at']
      end

      if attributes.key?(:'key')
        self.key = attributes[:'key']
      end

      if attributes.key?(:'product_type')
        self.product_type = attributes[:'product_type']
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'description')
        self.description = attributes[:'description']
      end

      if attributes.key?(:'slug')
        self.slug = attributes[:'slug']
      end

      if attributes.key?(:'categories')
        if (value = attributes[:'categories']).is_a?(Array)
          self.categories = value
        end
      end

      if attributes.key?(:'category_order_hints')
        self.category_order_hints = attributes[:'category_order_hints']
      end

      if attributes.key?(:'meta_title')
        self.meta_title = attributes[:'meta_title']
      end

      if attributes.key?(:'meta_description')
        self.meta_description = attributes[:'meta_description']
      end

      if attributes.key?(:'meta_keywords')
        self.meta_keywords = attributes[:'meta_keywords']
      end

      if attributes.key?(:'search_keywords')
        self.search_keywords = attributes[:'search_keywords']
      end

      if attributes.key?(:'has_staged_changes')
        self.has_staged_changes = attributes[:'has_staged_changes']
      end

      if attributes.key?(:'published')
        self.published = attributes[:'published']
      end

      if attributes.key?(:'master_variant')
        self.master_variant = attributes[:'master_variant']
      end

      if attributes.key?(:'variants')
        if (value = attributes[:'variants']).is_a?(Array)
          self.variants = value
        end
      end

      if attributes.key?(:'tax_category')
        self.tax_category = attributes[:'tax_category']
      end

      if attributes.key?(:'state')
        self.state = attributes[:'state']
      end

      if attributes.key?(:'review_rating_statistics')
        self.review_rating_statistics = attributes[:'review_rating_statistics']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          version == o.version &&
          created_at == o.created_at &&
          last_modified_at == o.last_modified_at &&
          key == o.key &&
          product_type == o.product_type &&
          name == o.name &&
          description == o.description &&
          slug == o.slug &&
          categories == o.categories &&
          category_order_hints == o.category_order_hints &&
          meta_title == o.meta_title &&
          meta_description == o.meta_description &&
          meta_keywords == o.meta_keywords &&
          search_keywords == o.search_keywords &&
          has_staged_changes == o.has_staged_changes &&
          published == o.published &&
          master_variant == o.master_variant &&
          variants == o.variants &&
          tax_category == o.tax_category &&
          state == o.state &&
          review_rating_statistics == o.review_rating_statistics
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, version, created_at, last_modified_at, key, product_type, name, description, slug, categories, category_order_hints, meta_title, meta_description, meta_keywords, search_keywords, has_staged_changes, published, master_variant, variants, tax_category, state, review_rating_statistics].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = CtSdk.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
