=begin
#Commercetools

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: undefined

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0

=end

require 'date'
require 'time'

module CtSdk
  class ReferenceTypeId
    CART = "cart".freeze
    CART_DISCOUNT = "cart-discount".freeze
    CATEGORY = "category".freeze
    CHANNEL = "channel".freeze
    CUSTOMER = "customer".freeze
    CUSTOMER_EMAIL_TOKEN = "customer-email-token".freeze
    CUSTOMER_GROUP = "customer-group".freeze
    CUSTOMER_PASSWORD_TOKEN = "customer-password-token".freeze
    DISCOUNT_CODE = "discount-code".freeze
    EXTENSION = "extension".freeze
    INVENTORY_ENTRY = "inventory-entry".freeze
    KEY_VALUE_DOCUMENT = "key-value-document".freeze
    ORDER = "order".freeze
    ORDER_EDIT = "order-edit".freeze
    PAYMENT = "payment".freeze
    PRODUCT = "product".freeze
    PRODUCT_DISCOUNT = "product-discount".freeze
    PRODUCT_TYPE = "product-type".freeze
    REVIEW = "review".freeze
    SHIPPING_METHOD = "shipping-method".freeze
    SHOPPING_LIST = "shopping-list".freeze
    STATE = "state".freeze
    STORE = "store".freeze
    SUBSCRIPTION = "subscription".freeze
    TAX_CATEGORY = "tax-category".freeze
    TYPE = "type".freeze
    ZONE = "zone".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = ReferenceTypeId.constants.select { |c| ReferenceTypeId::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #ReferenceTypeId" if constantValues.empty?
      value
    end
  end
end
