=begin
#Commercetools

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: undefined

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0

=end

require 'date'
require 'time'

module CtSdk
  class ResourceTypeId
    ASSET = "asset".freeze
    CATEGORY = "category".freeze
    CHANNEL = "channel".freeze
    CUSTOMER = "customer".freeze
    ORDER = "order".freeze
    ORDER_EDIT = "order-edit".freeze
    INVENTORY_ENTRY = "inventory-entry".freeze
    LINE_ITEM = "line-item".freeze
    CUSTOM_LINE_ITEM = "custom-line-item".freeze
    PRODUCT_PRICE = "product-price".freeze
    PAYMENT = "payment".freeze
    PAYMENT_INTERFACE_INTERACTION = "payment-interface-interaction".freeze
    REVIEW = "review".freeze
    SHOPPING_LIST = "shopping-list".freeze
    SHOPPING_LIST_TEXT_LINE_ITEM = "shopping-list-text-line-item".freeze
    DISCOUNT_CODE = "discount-code".freeze
    CART_DISCOUNT = "cart-discount".freeze
    CUSTOMER_GROUP = "customer-group".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = ResourceTypeId.constants.select { |c| ResourceTypeId::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #ResourceTypeId" if constantValues.empty?
      value
    end
  end
end
